# Generated by Django 5.2.8 on 2025-11-27 15:33

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("SALIDA", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "cantidad_movida",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Cantidad Movida",
                    ),
                ),
                (
                    "motivo_movimiento",
                    models.CharField(
                        choices=[
                            ("ENTREGA_CUENTAS", "Entrega Cuentas"),
                            ("ABONO_A_BASE", "Abono a Base"),
                            ("RECAUDO_OFICINA", "Recaudo Oficina"),
                            ("RECAUDO_PUNTO_FISICO", "Recaudo Punto Físico"),
                            ("GASOLINA", "Gasolina"),
                            ("ACEITE", "Aceite"),
                            (
                                "HERRAMIENTAS_COMPLEMENTARIAS",
                                "Herramientas Complementarias",
                            ),
                            ("REPARACION_VEHICULO", "Reparación Vehículo"),
                            ("CAFETERIA", "Cafetería"),
                            ("ELEMENTOS_ASEO", "Elementos Aseo"),
                            ("PRESTAMOS", "Préstamos"),
                            ("VENTA_EQUIPO", "Venta Equipo"),
                        ],
                        max_length=50,
                        verbose_name="Motivo de movimiento",
                    ),
                ),
                (
                    "info_adicional",
                    models.TextField(
                        blank=True, null=True, verbose_name="Información adicional"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "db_table": "CAJA",
            },
        ),
        migrations.CreateModel(
            name="SaldoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo Actual",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldo_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo Caja",
                "verbose_name_plural": "Saldos de Caja",
                "db_table": "SALDO_CAJA",
            },
        ),
    ]
