# Generated by Django 5.2.8 on 2025-11-27 15:33

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificaciones",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INFORMACION", "Información"),
                            ("ADVERTENCIA", "Advertencia"),
                            ("EXITO", "Éxito"),
                            ("FALLO", "Fallo"),
                            ("ERROR", "Error"),
                        ],
                        default="INFORMACION",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=50, verbose_name="titulo")),
                ("mensaje", models.TextField(verbose_name="mensaje")),
                ("leida", models.BooleanField(default=False, verbose_name="leida")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacion",
                "verbose_name_plural": "Notificaciones",
                "db_table": "NOTIFICACIONES",
                "ordering": ["-created"],
            },
        ),
    ]
