# Generated by Django 5.2.8 on 2025-11-27 15:33

import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="nombre de categoria"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripcion")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoria_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "CATEGORIA",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="nombre proveedor"),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "PROVEEDORES",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="nombre de producto"),
                ),
                ("descripcion", models.TextField(verbose_name="descripcion")),
                (
                    "precio_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="precio_compra",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="precio_venta",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="imagen del producto",
                    ),
                ),
                (
                    "medida",
                    models.CharField(
                        choices=[
                            ("ROLLOS", "Rollos"),
                            ("UNIDADES", "Unidades"),
                            ("PAQUETES", "Paquetes"),
                            ("METROS", "Metros"),
                        ],
                        default="UNIDADES",
                        max_length=20,
                        verbose_name="Medida del producto",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_categoria",
                        to="inventario.categoria",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_proveedor",
                        to="inventario.proveedor",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "PRODUCTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                (
                    "cantidad_movida",
                    models.PositiveIntegerField(verbose_name="Cantidad_movida"),
                ),
                (
                    "movimiento",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=50,
                        verbose_name="movimiento",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SURTIR", "Surtir"),
                            ("DESECHO", "Desecho"),
                            ("TICKET", "Ticket"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "motivo_personalizado",
                    models.TextField(
                        blank=True, null=True, verbose_name="motivo personalizado"
                    ),
                ),
                (
                    "codigo_ticket",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="codigo ticket",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_producto",
                        to="inventario.producto",
                        verbose_name="producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "usuario_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_usuario_destino",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Destino",
                    ),
                ),
                (
                    "usuario_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_usuario_origen",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "db_table": "STOCK",
            },
        ),
        migrations.CreateModel(
            name="StockActual",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_actual_producto",
                        to="inventario.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_actual_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Actual",
                "verbose_name_plural": "Stock Actual",
                "db_table": "STOCK_ACTUAL",
                "unique_together": {("usuario", "producto")},
            },
        ),
    ]
