# Generated by Django 5.2.8 on 2025-11-27 15:33

import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/fotos_perfil/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "foto_cedula_adelante",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/cedula_adelante/",
                        verbose_name="Foto cédula adelante",
                    ),
                ),
                (
                    "foto_cedula_atras",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/cedula_atras/",
                        verbose_name="Foto cédula atrás",
                    ),
                ),
                (
                    "foto_casa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/fotos_casa/",
                        verbose_name="Foto casa",
                    ),
                ),
                (
                    "foto_curso_altura",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/fotos_curso_altura/",
                        verbose_name="Foto curso de altura",
                    ),
                ),
                (
                    "foto_diploma_grado",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="perfiles/fotos_diploma_grado/",
                        verbose_name="Foto diploma grado",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GERENTE", "Gerente"),
                            ("ADMINISTRADOR", "Administrador"),
                            ("INGENIERO", "Ingeniero"),
                            ("TECNICO", "Técnico"),
                            ("AGENTE", "Agente"),
                            ("MARKETING", "Marketing"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "nivel_educativo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIMARIA", "Primaria"),
                            ("BASICA_SECUNDARIA", "Básica Secundaria"),
                            ("BACHILLER_ACADEMICO", "Bachiller Académico"),
                            ("TECNICO", "Técnico"),
                            ("INGENIERO", "Ingeniero"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Nivel educativo",
                    ),
                ),
                (
                    "curso_altura",
                    models.BooleanField(
                        default=False, verbose_name="Curso de altura aprobado"
                    ),
                ),
                (
                    "hijos",
                    models.BooleanField(default=False, verbose_name="Tiene hijos"),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASADO", "Casado"),
                            ("SOLTERO", "Soltero"),
                            ("UNION_LIBRE", "Unión Libre"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "conyugue",
                    models.BooleanField(default=False, verbose_name="Tiene cónyuge"),
                ),
                (
                    "nombre_conyugue",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre cónyuge",
                    ),
                ),
                (
                    "telefono_conyugue",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Teléfono conyugue",
                    ),
                ),
                (
                    "fecha_ingreso_empresa",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de ingreso a la empresa",
                    ),
                ),
                (
                    "fecha_retiro_empresa",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de retiro de la empresa",
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMBRE", "Hombre"),
                            ("MUJER", "Mujer"),
                            ("INCLUSIVO", "Inclusivo"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Género",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "db_table": "PERFILES",
            },
        ),
        migrations.CreateModel(
            name="VehiculoUsuario",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "foto_vehiculo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehiculos/foto_vehiculo/",
                        verbose_name="Foto vehículo",
                    ),
                ),
                (
                    "foto_soat",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehiculos/foto_soat/",
                        verbose_name="Foto SOAT",
                    ),
                ),
                (
                    "foto_tecnomecanico",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehiculos/foto_tecnomecanico/",
                        verbose_name="Foto Tecnomecánico",
                    ),
                ),
                (
                    "foto_tarjeta_propiedad",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehiculos/foto_tarjeta_propiedad/",
                        verbose_name="Foto tarjeta de propiedad",
                    ),
                ),
                (
                    "foto_pase_conducir",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vehiculos/foto_pase_conducir/",
                        verbose_name="Foto pase de conducir",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Marca"
                    ),
                ),
                (
                    "placas_vehiculo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Placas"
                    ),
                ),
                (
                    "soat",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de vencimiento del SOAT",
                    ),
                ),
                (
                    "tecnomecanico",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de vencimiento del Tecnomecánico",
                    ),
                ),
                (
                    "tarjeta_propiedad",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de vencimiento de la Tarjeta de Propiedad",
                    ),
                ),
                (
                    "pase_conducir",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de vencimiento del Pase de Conducir",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOTO", "Moto"),
                            ("CARRO", "Carro"),
                            ("CAMIONETA", "Camioneta"),
                            ("CAMION", "Camion"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="tipo de vehiculo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos_usuario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "VEHICULO",
            },
        ),
    ]
